### ISSUE TITLE
Documentación problemática

### ISSUE THREAD

**Issue by gonso0** [jjegc/Cabina-de-votacion#1]
Version del código heredado: 1.0 (original)
Versión IDE: Eclipse Neon Python 4.6.0
Versión de documentación. 1.0 (original)

La documentación ofrecida es nula, lo cual impide que se pueda entender el codigo y desplegar el subsistema.

**Comment by gdelgadochaves** [comment]
Actualización: a fecha actual comienza el estudio del sistema a desplegar para desarrollar documentación base.

**Comment by gdelgadochaves** [comment]
La documentación base queda resuelta. Se ha resuelto en un documento de interés sencillo, a la espera de operar con información que permita aclarar si será necesario desarrollar un documento especializado.
