### ISSUE TITLE
Problema al redirigir a la url /cabine/save/vote.do

### ISSUE THREAD

**Issue by JHeavy** [jjegc/Cabina-de-votacion#3]
Existe un problema al redirigir a la siguiente url, "/cabine/save/vote.do", que tiene que ver con la integración del grupo de creacion de votos.

Tomcat version 8.0
Version Java 1.8
Maven version 3.5
Usando el navegador Opera
SO windows 10

**Comment by adrisanyes** [comment]
Se ha solucionado dicho problema con dicha url. El problema era debido a la mala integración con otro de los subsistemas. La issue queda cerrada.
